# Generated by Django 4.2.6 on 2023-11-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_desc_sensor_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='value',
            new_name='temperature',
        ),
    ]
